"""create login history table

Revision ID: 136b1260bb62
Revises: 10ec31ff1d8b
Create Date: 2026-09-02 14:29:03.482828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136b1260bb62'
down_revision = '10ec31ff1d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    # ### end Alembic commands ###
