"""add blog post creator

Revision ID: 4ede988189dc
Revises: 811e3a867e43
Create Date: 2026-09-02 19:12:44.441807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ede988189dc'
down_revision = '811e3a867e43'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_by_id",
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            None,
            "users",
            ["created_by_id"],
            ["id"]
        )

    op.execute(
        "UPDATE blog_posts SET created_by_id = 1 WHERE created_by_id IS NULL"
    )

    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by_id",
            existing_type=sa.Integer(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
