"""change blog author to text

Revision ID: 811e3a867e43
Revises: 9d3c182810cb
Create Date: 2026-09-02 18:26:01.488110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811e3a867e43'
down_revision = '9d3c182810cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=150), nullable=False))
        batch_op.drop_constraint(batch_op.f('blog_posts_author_id_fkey'), type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('blog_posts_author_id_fkey'), 'users', ['author_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###
