"""add blog post visibility

Revision ID: 894963b002ef
Revises: 4ede988189dc
Create Date: 2026-09-03 13:14:59.859547

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "894963b002ef"
down_revision = "4ede988189dc"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("visibility", sa.String(length=20), nullable=True)
        )

    op.execute(
        "UPDATE blog_posts SET visibility = 'private' " "WHERE visibility IS NULL"
    )

    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.alter_column(
            "visibility", existing_type=sa.String(length=20), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.drop_column("visibility")

    # ### end Alembic commands ###
