"""Remove duplicate author fields

Revision ID: 8a3e3a8eae51
Revises: 51b655a00247
Create Date: 2026-09-05 12:24:55.698729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e3a8eae51'
down_revision = '51b655a00247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('author')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=150), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
